// Lowercase pattern, severity (2 problem, 1 warning), title, explanation, layer.
// Patterns are matched against the lowercased response body.

// lowercase pattern, severity, title, detail, layer
const _sigsCore = <(String, int, String, String, String)>[
  // Databases and dependencies
  ('error establishing a database connection', 2, 'WordPress cannot reach its database', 'MySQL is down, overloaded or the credentials changed.', 'Database / dependency'),
  ('sqlstate', 2, 'SQL error in the response', 'A database query failed. Check the query and database health.', 'Database / dependency'),
  ('could not connect to server', 2, 'Database connection failed', 'The app could not open a connection to its database.', 'Database / dependency'),
  ('too many connections', 2, 'Database connection limit reached', 'Pool or server max connections exhausted. Close leaks or raise limits.', 'Database / dependency'),
  ('pooltimeout', 2, 'Connection pool exhausted', 'All pooled connections are busy. Look for slow queries or leaks.', 'Database / dependency'),
  ('mysql server has gone away', 2, 'MySQL connection dropped', 'The server closed an idle or oversized connection.', 'Database / dependency'),
  ('lock wait timeout exceeded', 2, 'Database lock timeout', 'A long transaction is blocking others.', 'Database / dependency'),
  ('deadlock found', 2, 'Database deadlock', 'Two transactions blocked each other.', 'Database / dependency'),
  ('mongoerror', 2, 'MongoDB error', 'The app failed talking to MongoDB.', 'Database / dependency'),
  ('redis connection', 2, 'Redis connection problem', 'Redis is unreachable or its pool is exhausted.', 'Database / dependency'),
  ('redis.exceptions', 2, 'Redis error', 'The Python Redis client raised an error.', 'Database / dependency'),
  ("can't reach database server", 2, 'Prisma cannot reach the database', 'Check the database URL and that the server is up.', 'Database / dependency'),
  ('econnrefused', 2, 'A backend refused a connection', 'A dependency (database, cache or API) is not accepting connections.', 'Database / dependency'),
  // Application crashes
  ('traceback (most recent call last)', 2, 'Python stack trace in response', 'Read the last line of the traceback for the exception.', 'Origin server'),
  ('debug = true', 1, 'Django debug page exposed', 'DEBUG is on in production. The page may show the exception.', 'Origin server'),
  ('whoops, looks like something went wrong', 2, 'Laravel error page', 'Unhandled PHP exception. Check storage/logs/laravel.log.', 'Origin server'),
  ('whitelabel error page', 2, 'Spring Boot error page', 'An unhandled exception reached the default handler.', 'Origin server'),
  ('fatal error:', 2, 'PHP fatal error', 'Check the PHP error log.', 'Origin server'),
  ('parse error:', 2, 'PHP parse error', 'A syntax error in deployed code.', 'Origin server'),
  ('allowed memory size', 2, 'PHP out of memory', 'Raise memory_limit or fix the leak.', 'Origin server'),
  ('maximum execution time', 2, 'PHP script timed out', 'A request ran longer than max_execution_time.', 'Origin server'),
  ('there has been a critical error on this website', 2, 'WordPress critical error', 'A plugin or theme crashed. Enable WP_DEBUG to see which.', 'Origin server'),
  ('application error: a server-side exception has occurred', 2, 'Next.js server exception', 'Check server logs using the digest shown on the page.', 'Origin server'),
  ("we're sorry, but something went wrong", 2, 'Rails error page', 'Check log/production.log.', 'Origin server'),
  ("server error in '/' application", 2, 'ASP.NET unhandled error', 'Check the event log or enable custom errors detail.', 'Origin server'),
  ('http error 500.', 2, 'IIS 500 error', 'The IIS site returned an error. See the sub-status code.', 'Origin server'),
  ('http status 500', 2, 'Tomcat 500 error', 'Check catalina.out for the stack trace.', 'Origin server'),
  ('nullpointerexception', 2, 'Java NullPointerException', 'Unhandled null in server code.', 'Origin server'),
  ('java.lang.outofmemoryerror', 2, 'Java out of memory', 'Heap exhausted. Raise -Xmx or fix the leak.', 'Origin server'),
  ('cannot find module', 2, 'Node module missing', 'A dependency was not installed in the deployment.', 'Origin server'),
  ('typeerror:', 2, 'JavaScript TypeError on server', 'Unhandled error in Node code.', 'Origin server'),
  ('referenceerror:', 2, 'JavaScript ReferenceError on server', 'Unhandled error in Node code.', 'Origin server'),
  ('an error occurred in the application and your page could not be served', 2, 'Heroku application error', 'The dyno crashed or timed out. Run heroku logs --tail.', 'Origin server'),
  ('application failed to respond', 2, 'Railway app not responding', 'The service crashed or listens on the wrong port.', 'Origin server'),
  ('http response was malformed or connection to the instance had an error', 2, 'Cloud Run container failed', 'The container crashed or ignored the PORT variable.', 'Origin server'),
  ('function_invocation_failed', 2, 'Vercel function crashed', 'Check function logs in the Vercel dashboard.', 'Origin server'),
  ('function_invocation_timeout', 2, 'Vercel function timed out', 'The function exceeded its time limit.', 'Origin server'),
  ('deployment_not_found', 2, 'Vercel deployment missing', 'The deployment was removed or the domain points to nothing.', 'Origin server'),
  ('currently stopped', 2, 'Azure web app is stopped', 'Start the app service in the Azure portal.', 'Origin server'),
  ("there isn't a github pages site here", 2, 'GitHub Pages site missing', 'Pages is not enabled or the build failed.', 'Origin server'),
  ('account has been suspended', 2, 'Hosting account suspended', 'Contact the host: unpaid bill or abuse suspension.', 'Origin server'),
  ('resource limit is reached', 2, 'Hosting resource limit hit', 'Shared hosting CPU or memory quota exceeded.', 'Origin server'),
  ('bandwidth limit exceeded', 2, 'Bandwidth quota exceeded', 'The hosting plan transfer quota is used up.', 'Origin server'),
  ('under maintenance', 1, 'Maintenance page', 'The site is deliberately offline.', 'Origin server'),
  ('maintenance mode', 1, 'Maintenance mode', 'The site is deliberately offline.', 'Origin server'),
  ('welcome to nginx!', 1, 'Default nginx page', 'The app is not deployed or the virtual host is misrouted.', 'Origin server'),
  ('apache2 ubuntu default page', 1, 'Default Apache page', 'The app is not deployed or the virtual host is misrouted.', 'Origin server'),
  ('this domain is for sale', 1, 'Parked domain', 'The domain is parked, expired or not pointed at your server.', 'DNS'),
  ('domain parking', 1, 'Parked domain', 'The domain is parked, expired or not pointed at your server.', 'DNS'),
  ('cannot get /', 1, 'Express route not found', 'The Node app is up but has no route for this path.', 'Origin server'),
  // Proxies and load balancers
  ('upstream connect error or disconnect/reset before headers', 2, 'Envoy/Istio cannot reach the service', 'The pod is down, restarting or refusing connections.', 'Proxy / load balancer'),
  ('no healthy upstream', 2, 'No healthy backends', 'All backends failed health checks.', 'Proxy / load balancer'),
  ('upstream request timeout', 2, 'Proxy timed out waiting for the app', 'The app is slow or hung.', 'Proxy / load balancer'),
  ('while connecting to upstream', 2, 'nginx cannot connect to upstream', 'The app process is down or listens elsewhere.', 'Proxy / load balancer'),
  ('upstream timed out', 2, 'nginx upstream timeout', 'The app took longer than proxy_read_timeout.', 'Proxy / load balancer'),
  ('upstream prematurely closed connection', 2, 'App closed the connection early', 'The app crashed mid-request.', 'Proxy / load balancer'),
  ('default backend - 404', 2, 'Kubernetes ingress has no matching route', 'Check the Ingress host, path and service.', 'Proxy / load balancer'),
  ('no server is available to handle this request', 2, 'HAProxy has no live backend', 'All servers in the pool are down.', 'Proxy / load balancer'),
  ('invalid response from an upstream server', 2, 'Apache proxy got an invalid reply', 'The backend returned something malformed or crashed.', 'Proxy / load balancer'),
  ('guru meditation', 2, 'Varnish backend failure', 'Varnish could not get a response from the backend.', 'Proxy / load balancer'),
  // Firewalls and bot protection
  ('attention required! | cloudflare', 1, 'Cloudflare blocked the probe', 'This is a challenge, not an outage. Real users may be fine.', 'Firewall / bot protection'),
  ('just a moment...', 1, 'Cloudflare browser challenge', 'The probe cannot pass this check.', 'Firewall / bot protection'),
  ('error 1020', 1, 'Cloudflare firewall rule blocked access', 'A WAF rule matched this request.', 'Firewall / bot protection'),
  ('error 1015', 1, 'Cloudflare rate limit hit', 'Too many requests from this IP.', 'Firewall / bot protection'),
  ('error 1010', 1, 'Cloudflare blocked the browser signature', 'The client was flagged as automated.', 'Firewall / bot protection'),
  ('error 1033', 2, 'Cloudflare Tunnel is down', 'The cloudflared connector is not running.', 'Origin server'),
  ('error 1016', 2, 'Cloudflare cannot resolve the origin', 'The origin DNS record is wrong or missing.', 'DNS'),
  ('error 1101', 2, 'Cloudflare Worker threw an exception', 'Check the Worker logs.', 'Origin server'),
  ('error 1102', 2, 'Cloudflare Worker exceeded resource limits', 'CPU or memory limit hit.', 'Origin server'),
  ('errors.edgesuite.net', 1, 'Akamai blocked the request', 'Access denied by the CDN edge.', 'Firewall / bot protection'),
  ('incapsula incident', 1, 'Imperva blocked the request', 'Access denied by the WAF.', 'Firewall / bot protection'),
  ('sucuri website firewall', 1, 'Sucuri blocked the request', 'Access denied by the WAF.', 'Firewall / bot protection'),
  ('captcha', 1, 'CAPTCHA challenge', 'Bot protection is challenging the probe.', 'Firewall / bot protection'),
];

const _sigsDeep = <(String, int, String, String, String)>[
  ("psycopg2.operationalerror", 2, "PostgreSQL connection error", "The Python app could not talk to PostgreSQL: server down, wrong host, or too many connections.", "Database / dependency"),
  ("psycopg2.errors", 2, "PostgreSQL query error", "A query failed. Check migrations and the query in the stack trace.", "Database / dependency"),
  ("pg::connectionbad", 2, "PostgreSQL connection refused (Rails)", "The Rails app cannot open a database connection.", "Database / dependency"),
  ("remaining connection slots are reserved", 2, "PostgreSQL out of connections", "max_connections is exhausted. Use a pooler such as PgBouncer or close leaked connections.", "Database / dependency"),
  ("the database system is starting up", 2, "PostgreSQL is starting up", "The database just restarted and is not ready yet.", "Database / dependency"),
  ("the database system is in recovery mode", 2, "PostgreSQL in recovery", "The database is replaying logs after a crash.", "Database / dependency"),
  ("canceling statement due to statement timeout", 2, "Database statement timeout", "A query ran past statement_timeout. Find and optimise it.", "Database / dependency"),
  ("canceling statement due to conflict with recovery", 2, "Replica query cancelled", "A read replica cancelled a query because of replication conflicts.", "Database / dependency"),
  ("sequelizeconnectionerror", 2, "Sequelize cannot connect", "The Node app could not reach its SQL database.", "Database / dependency"),
  ("sequelizedatabaseerror", 2, "Sequelize query failed", "A SQL query raised an error. Check the migration state.", "Database / dependency"),
  ("queryfailederror", 2, "TypeORM query failed", "A query failed. Often a missing table or column after a deploy.", "Database / dependency"),
  ("no such table", 2, "Table missing", "A migration has not run on this database.", "Database / dependency"),
  ("unknown column", 2, "Column missing", "The code expects a column the database does not have. A migration did not run.", "Database / dependency"),
  ("base table or view not found", 2, "Table or view missing (Laravel)", "A migration has not run on this database.", "Database / dependency"),
  ("activerecord::pendingmigrationerror", 2, "Rails migrations pending", "Run db:migrate. The deploy shipped code that needs a schema change.", "Database / dependency"),
  ("activerecord::connectionnotestablished", 2, "Rails has no database connection", "Check database.yml / DATABASE_URL and that the database is up.", "Database / dependency"),
  ("activerecord::statementinvalid", 2, "Rails SQL statement invalid", "A query failed. Check schema and migrations.", "Database / dependency"),
  ("sqlalchemy.exc", 2, "SQLAlchemy error", "A database call failed in a Python app.", "Database / dependency"),
  ("could not obtain a connection from the pool", 2, "Connection pool exhausted", "All pooled connections are busy. Look for leaks or slow queries.", "Database / dependency"),
  ("hikaripool", 2, "HikariCP pool problem", "Java connection pool timed out or is exhausted.", "Database / dependency"),
  ("connection is not available, request timed out", 2, "Connection pool timeout", "Requests waited for a database connection and gave up.", "Database / dependency"),
  ("communications link failure", 2, "MySQL link failure", "The Java app lost its connection to MySQL.", "Database / dependency"),
  ("sqlserverexception", 2, "SQL Server error", "A SQL Server call failed. Check the server and credentials.", "Database / dependency"),
  ("login failed for user", 2, "Database login failed", "Wrong credentials or the account was disabled or rotated.", "Database / dependency"),
  ("access denied for user", 2, "Database access denied", "Credentials changed or the user lost privileges.", "Database / dependency"),
  ("password authentication failed", 2, "Database password rejected", "The database password was rotated or is wrong in the deployment.", "Database / dependency"),
  ("ora-12541", 2, "Oracle listener is down", "No Oracle listener on that host and port.", "Database / dependency"),
  ("mongoserverselectionerror", 2, "MongoDB unreachable", "The driver found no usable MongoDB server.", "Database / dependency"),
  ("mongonetworkerror", 2, "MongoDB network error", "The connection to MongoDB dropped or timed out.", "Database / dependency"),
  ("server selection timed out", 2, "MongoDB server selection timed out", "Replica set down, wrong URI, or IP not allow-listed.", "Database / dependency"),
  ("sqlite_busy", 2, "SQLite is locked", "Too many writers for SQLite. Move to a client-server database.", "Database / dependency"),
  ("database is locked", 2, "SQLite database locked", "Concurrent writes blocked each other.", "Database / dependency"),
  ("read-only transaction", 2, "Database is read-only", "The primary failed over or the volume is read-only.", "Database / dependency"),
  ("noauth authentication required", 2, "Redis needs a password", "The app connects without the Redis password.", "Database / dependency"),
  ("loading redis is loading the dataset", 2, "Redis is still loading", "Redis just restarted and is loading its data.", "Database / dependency"),
  ("oom command not allowed", 2, "Redis out of memory", "Redis hit maxmemory and refuses writes.", "Database / dependency"),
  ("redis::cannotconnecterror", 2, "Redis unreachable (Ruby)", "The Redis server is down or the URL is wrong.", "Database / dependency"),
  ("no living connections", 2, "Elasticsearch unreachable", "The search cluster is down or blocked.", "Database / dependency"),
  ("search_phase_execution_exception", 2, "Elasticsearch query failed", "A search request failed. Check cluster health.", "Database / dependency"),
  ("provisionedthroughputexceededexception", 2, "DynamoDB throttled", "Provisioned capacity exhausted. Raise capacity or use on-demand.", "Database / dependency"),
  ("throttlingexception", 2, "AWS API throttling", "The app is calling an AWS API too fast.", "Database / dependency"),
  ("brokers not available", 2, "Kafka brokers unavailable", "The app cannot reach any Kafka broker.", "Database / dependency"),
  ("amqp connection", 2, "RabbitMQ connection problem", "The message broker is down or refusing connections.", "Database / dependency"),
  ("memcached", 1, "Memcached mentioned in error", "A cache call may have failed. Check the cache server.", "Database / dependency"),
  ("getaddrinfo enotfound", 2, "App cannot resolve a dependency hostname", "The server could not look up a backend name. DNS inside the VPC or a typo in config.", "Database / dependency"),
  ("could not resolve host", 2, "App cannot resolve a dependency host", "An outbound DNS lookup failed on the server.", "Database / dependency"),
  ("name or service not known", 2, "Server-side DNS failure", "An outbound DNS lookup failed on the server.", "Database / dependency"),
  ("econnreset", 2, "A backend reset the connection", "A dependency dropped the connection mid-request.", "Database / dependency"),
  ("etimedout", 2, "A backend connection timed out", "A dependency did not answer in time.", "Database / dependency"),
  ("socket hang up", 2, "Backend closed the socket", "A dependency closed the connection without replying.", "Database / dependency"),
  ("context deadline exceeded", 2, "Go service hit its deadline", "A call to a dependency took longer than its timeout.", "Database / dependency"),
  ("dial tcp", 2, "Go service could not dial a dependency", "The target host refused or did not answer.", "Database / dependency"),
  ("unable to verify the first certificate", 2, "App rejects a dependency certificate", "TLS verification to a backend failed. Chain is incomplete.", "Database / dependency"),
  ("self signed certificate in certificate chain", 2, "App rejects a self-signed certificate", "A backend uses a certificate the app does not trust.", "Database / dependency"),
  ("certificate_verify_failed", 2, "Backend certificate verification failed", "The app cannot verify a dependency's TLS certificate.", "Database / dependency"),
  ("connection pool is full", 2, "HTTP client pool exhausted", "Too many concurrent outbound requests.", "Database / dependency"),
  ("exceeded your current quota", 2, "Third-party quota exceeded", "An external API plan limit was reached.", "Database / dependency"),
  ("payment required", 2, "Billing blocked a service", "An account used by the app has unpaid charges.", "Database / dependency"),
  ("modulenotfounderror", 2, "Python module missing", "A dependency was not installed in this deployment.", "Origin server"),
  ("importerror:", 2, "Python import failed", "A package is missing or the wrong version.", "Origin server"),
  ("classnotfoundexception", 2, "Java class not found", "A jar is missing from the deployment.", "Origin server"),
  ("noclassdeffounderror", 2, "Java class definition missing", "Classpath or dependency mismatch after a deploy.", "Origin server"),
  ("nosuchmethoderror", 2, "Java method missing", "Two library versions conflict.", "Origin server"),
  ("stackoverflowerror", 2, "Java stack overflow", "Runaway recursion in server code.", "Origin server"),
  ("outofmemoryerror", 2, "Out of memory", "The process ran out of heap. Raise limits or fix the leak.", "Origin server"),
  ("javascript heap out of memory", 2, "Node heap exhausted", "Raise --max-old-space-size or fix the leak.", "Origin server"),
  ("maximum call stack size exceeded", 2, "Node stack overflow", "Runaway recursion in server code.", "Origin server"),
  ("unhandledpromiserejection", 2, "Unhandled promise rejection", "A rejected promise crashed or broke the handler.", "Origin server"),
  ("nomethoderror", 2, "Ruby NoMethodError", "Unhandled nil or missing method in a Rails app.", "Origin server"),
  ("actioncontroller::routingerror", 1, "Rails route missing", "No route matches this path.", "Origin server"),
  ("actionview::template::error", 2, "Rails template error", "A view raised an exception while rendering.", "Origin server"),
  ("rack::timeout", 2, "Rack request timeout", "A request exceeded the Rack timeout. Look for slow work or queries.", "Origin server"),
  ("attributeerror:", 2, "Python AttributeError", "An unhandled error in application code.", "Origin server"),
  ("keyerror:", 2, "Python KeyError", "A missing key or setting in application code.", "Origin server"),
  ("zerodivisionerror", 2, "Python ZeroDivisionError", "An unhandled error in application code.", "Origin server"),
  ("improperlyconfigured", 2, "Django misconfigured", "A required Django setting is missing or wrong.", "Origin server"),
  ("invalid http_host header", 2, "Django rejects the Host header", "ALLOWED_HOSTS does not include this domain.", "Proxy / load balancer"),
  ("disallowedhost", 2, "Django DisallowedHost", "Add the domain to ALLOWED_HOSTS.", "Proxy / load balancer"),
  ("the debugger caught an exception", 2, "Flask debugger exposed", "Debug mode is on in production and an exception occurred.", "Origin server"),
  ("werkzeug.exceptions", 2, "Werkzeug exception", "A Flask or Werkzeug error reached the client.", "Origin server"),
  ("call to undefined function", 2, "PHP undefined function", "An extension is missing or code is mismatched.", "Origin server"),
  ("class not found", 2, "PHP class not found", "Autoload is stale or a package is missing. Run composer install.", "Origin server"),
  ("uncaught error", 2, "PHP uncaught error", "An exception was not handled. Check the PHP error log.", "Origin server"),
  ("uncaught exception", 2, "PHP uncaught exception", "An exception was not handled. Check the PHP error log.", "Origin server"),
  ("no application encryption key has been specified", 2, "Laravel APP_KEY missing", "Set APP_KEY in the environment and clear config cache.", "Origin server"),
  ("primary script unknown", 2, "PHP-FPM cannot find the script", "The document root or script path in the web server is wrong.", "Proxy / load balancer"),
  ("no input file specified", 2, "PHP cannot find the file", "Wrong root path or the code was not deployed.", "Proxy / load balancer"),
  ("system.nullreferenceexception", 2, ".NET NullReferenceException", "Unhandled null in server code.", "Origin server"),
  ("an unhandled exception occurred while processing the request", 2, "ASP.NET Core unhandled exception", "Developer error page is exposed. Read the exception.", "Origin server"),
  ("http error 502.5", 2, "ASP.NET Core process failure", "The app failed to start behind IIS.", "Origin server"),
  ("http error 500.30", 2, "ASP.NET Core start failure", "The app crashed during startup. Check stdout logs.", "Origin server"),
  ("http error 500.19", 2, "IIS configuration error", "web.config is invalid or a module is missing.", "Origin server"),
  ("http error 503. the service is unavailable", 2, "IIS application pool stopped", "The pool crashed or was stopped. Restart it and read the event log.", "Origin server"),
  ("bad request - invalid hostname", 2, "IIS host binding missing", "The site has no binding for this hostname.", "Proxy / load balancer"),
  ("phusion passenger", 2, "Passenger error page", "The app failed to start under Passenger.", "Origin server"),
  ("web application could not be started", 2, "App failed to start", "Startup crashed. Read the log shown on the page.", "Origin server"),
  ("worker timeout", 2, "Gunicorn worker timed out", "A worker was killed for running too long.", "Origin server"),
  ("uwsgi_response_write_body", 2, "uWSGI write error", "The client or proxy closed the connection mid-response.", "Origin server"),
  ("segmentation fault", 2, "Process segfault", "A native extension crashed the process.", "Origin server"),
  ("permission denied", 1, "Permission denied on the server", "The app user cannot read a file or bind a port.", "Origin server"),
  ("eacces", 2, "File permission error", "The app user lacks access to a path.", "Origin server"),
  ("eaddrinuse", 2, "Port already in use", "Two processes fight over one port. Kill the stale one.", "Origin server"),
  ("too many open files", 2, "File descriptor limit hit", "Raise ulimit -n or fix the leak.", "Origin server"),
  ("no space left on device", 2, "Disk is full", "The server has no free disk space. Clear logs and temp files.", "Origin server"),
  ("enospc", 2, "Disk or inotify limit hit", "No space left, or the watcher limit was reached.", "Origin server"),
  ("missing environment variable", 2, "Environment variable missing", "A required setting was not set in this environment.", "Origin server"),
  ("secret_key", 1, "Secret key referenced in error", "A missing SECRET_KEY often breaks startup.", "Origin server"),
  ("invalid configuration", 2, "Invalid configuration", "The app rejected its config at startup.", "Origin server"),
  ("configuration error", 1, "Configuration error", "A setting is wrong or missing.", "Origin server"),
  ("no such app", 2, "Heroku app does not exist", "The app was deleted or the domain points to the wrong app.", "Origin server"),
  ("there is nothing here, yet", 2, "Netlify/hosting site is empty", "Nothing is deployed to this site.", "Origin server"),
  ("site not found", 2, "Hosting site not found", "The domain is not attached to any site.", "Origin server"),
  ("the specified bucket does not exist", 2, "S3 bucket missing", "The bucket was deleted or renamed.", "Origin server"),
  ("nosuchbucket", 2, "S3 bucket missing", "The bucket was deleted or renamed.", "Origin server"),
  ("nosuchkey", 2, "S3 object missing", "The file is not in the bucket.", "Origin server"),
  ("<code>accessdenied</code>", 2, "S3 access denied", "Bucket policy or object ACL blocks public reads.", "Origin server"),
  ("firebase hosting setup complete", 1, "Firebase default page", "Nothing has been deployed yet.", "Origin server"),
  ("train has not arrived at the station", 2, "Railway app not found", "The service is not deployed at this domain.", "Origin server"),
  ("this service has been suspended", 2, "Render service suspended", "Billing or usage limits suspended the service.", "Origin server"),
  ("your free instance is spinning down", 1, "Render free instance asleep", "The first request wakes it; it is slow, not broken.", "Origin server"),
  ("application is not available", 2, "OpenShift route has no app", "The route exists but no pod is serving.", "Proxy / load balancer"),
  ("the application is currently not serving requests", 2, "App Engine not serving", "No version is serving traffic.", "Origin server"),
  ("error 403 - this web app is stopped", 2, "Azure web app stopped", "Start the app service.", "Origin server"),
  ("your app service is up and running", 1, "Azure default page", "No code is deployed to the app service.", "Origin server"),
  ("our services aren't available right now", 2, "Azure Front Door has no healthy origin", "All origins failed health probes.", "Proxy / load balancer"),
  ("the request could not be satisfied", 2, "CloudFront could not reach the origin", "The origin is down, slow or rejecting CloudFront.", "Proxy / load balancer"),
  ("generated by cloudfront", 2, "CloudFront error page", "The edge could not get a valid reply from the origin.", "Proxy / load balancer"),
  ("bad request: error from cloudfront", 2, "CloudFront bad request", "The edge rejected the request.", "Proxy / load balancer"),
  ("the server encountered an error and could not complete your request", 2, "Google frontend error", "An app on Google Cloud returned an error.", "Origin server"),
  ("ngrok", 1, "ngrok tunnel page", "A dev tunnel is offline or expired.", "Origin server"),
  ("this site has been disabled", 2, "Site disabled", "The host disabled this site.", "Origin server"),
  ("this account has been suspended", 2, "Account suspended", "The hosting account was suspended.", "Origin server"),
  ("account suspended", 2, "Account suspended", "The hosting account was suspended.", "Origin server"),
  ("domain has been suspended", 2, "Domain suspended", "The registrar suspended the domain.", "DNS"),
  ("trial has expired", 2, "Trial expired", "A trial plan ended and the site went offline.", "Origin server"),
  ("coming soon", 1, "Coming soon page", "A placeholder page replaced the app.", "Origin server"),
  ("under construction", 1, "Under construction page", "A placeholder page replaced the app.", "Origin server"),
  ("index of /", 1, "Directory listing", "The web root has no app or index file.", "Origin server"),
  ("it works!", 1, "Default web server page", "The web server is up but the app is not deployed.", "Origin server"),
  ("test page for the apache http server", 1, "Default Apache test page", "The vhost is not pointing at the app.", "Origin server"),
  ("test page for the nginx", 1, "Default nginx test page", "The server block is not pointing at the app.", "Origin server"),
  ("welcome to openresty", 1, "Default OpenResty page", "The app is not deployed behind it.", "Origin server"),
  ("welcome to tomcat", 1, "Default Tomcat page", "The webapp is not deployed.", "Origin server"),
  ("default web site page", 1, "Default hosting page", "The domain is not bound to a site.", "Origin server"),
  ("there is no website configured at this address", 2, "No website configured", "The domain is not attached to any site on this server.", "Proxy / load balancer"),
  ("domain is not configured", 2, "Domain not configured", "The host does not know this domain.", "Proxy / load balancer"),
  ("no site configured", 2, "No site configured", "The host does not know this domain.", "Proxy / load balancer"),
  ("502 bad gateway", 2, "Bad gateway page", "A proxy could not get a valid reply from the app behind it.", "Proxy / load balancer"),
  ("504 gateway time-out", 2, "Gateway time-out page", "The app behind the proxy did not answer in time.", "Proxy / load balancer"),
  ("503 service temporarily unavailable", 2, "Service temporarily unavailable", "The proxy has no backend able to answer.", "Proxy / load balancer"),
  ("service temporarily unavailable", 2, "Service temporarily unavailable", "The server is overloaded or down for maintenance.", "Proxy / load balancer"),
  ("no available server", 2, "Traefik has no available server", "No backend is registered or healthy.", "Proxy / load balancer"),
  ("no endpoints available for service", 2, "Kubernetes service has no endpoints", "No ready pods back the service.", "Proxy / load balancer"),
  ("no live upstreams while connecting", 2, "nginx has no live upstream", "All upstreams are marked down.", "Proxy / load balancer"),
  ("connect() failed (111", 2, "nginx upstream refused", "Nothing listens on the upstream port.", "Proxy / load balancer"),
  ("connect() failed (113", 2, "nginx upstream unreachable", "No route to the upstream host.", "Proxy / load balancer"),
  ("recv() failed (104", 2, "Upstream reset the connection", "The app crashed or closed the socket mid-response.", "Proxy / load balancer"),
  ("client intended to send too large body", 2, "Request body too large", "client_max_body_size is too small for this request.", "Proxy / load balancer"),
  ("request entity too large", 2, "Request entity too large", "A proxy or server size limit was exceeded.", "Proxy / load balancer"),
  ("request header or cookie too large", 2, "Request header or cookie too large", "Cookies grew past the header limit. Clear cookies or raise the limit.", "Proxy / load balancer"),
  ("request-uri too large", 2, "URL too large", "The URL is longer than the server allows.", "Proxy / load balancer"),
  ("the plain http request was sent to https port", 2, "HTTP sent to an HTTPS port", "The proxy is misconfigured or the URL scheme is wrong.", "Proxy / load balancer"),
  ("err_too_many_redirects", 2, "Too many redirects", "A redirect loop between HTTP/HTTPS or www rules.", "Proxy / load balancer"),
  ("the requested url was rejected", 1, "F5 WAF rejected the request", "A BIG-IP policy blocked this request.", "Firewall / bot protection"),
  ("mod_security", 1, "ModSecurity blocked the request", "A WAF rule matched.", "Firewall / bot protection"),
  ("you don't have permission to access", 1, "Apache denied access", "Directory permissions or Require rules block this path.", "Firewall / bot protection"),
  ("sorry, you have been blocked", 1, "Cloudflare blocked this client", "A WAF rule blocks the probe.", "Firewall / bot protection"),
  ("checking your browser before accessing", 1, "Browser check interstitial", "A challenge page the probe cannot pass.", "Firewall / bot protection"),
  ("enable javascript and cookies to continue", 1, "Managed challenge page", "Cloudflare asks for a real browser.", "Firewall / bot protection"),
  ("verifying you are human", 1, "Human verification page", "Bot protection challenges automated clients.", "Firewall / bot protection"),
  ("pardon our interruption", 1, "Imperva challenge page", "Bot protection blocked the probe.", "Firewall / bot protection"),
  ("perimeterx", 1, "PerimeterX bot defence", "Automated traffic is challenged.", "Firewall / bot protection"),
  ("datadome", 1, "DataDome bot defence", "Automated traffic is challenged.", "Firewall / bot protection"),
  ("access denied", 1, "Access denied page", "A firewall or permission rule rejected the request.", "Firewall / bot protection"),
  ("request blocked", 1, "Request blocked", "A security rule rejected the request.", "Firewall / bot protection"),
  ("rate limit exceeded", 1, "Rate limit exceeded", "Too many requests from this client.", "Request / auth"),
  ("too many requests", 1, "Too many requests", "Too many requests from this client.", "Request / auth"),
  ("you are being rate limited", 1, "Rate limited", "Too many requests from this client.", "Request / auth"),
  ("csrf verification failed", 1, "CSRF check failed", "A token or cookie is missing.", "Request / auth"),
  ("csrf token mismatch", 1, "CSRF token mismatch", "Session or cookie problem.", "Request / auth"),
  ("page expired", 1, "Page expired", "Session token expired.", "Request / auth"),
  ("jwt expired", 1, "JWT expired", "The token expired. Not an outage.", "Request / auth"),
  ("invalid api key", 1, "Invalid API key", "The credentials were rejected.", "Request / auth"),
  ("invalid_grant", 1, "OAuth grant invalid", "The refresh or auth code is no longer valid.", "Request / auth"),
  ("session expired", 1, "Session expired", "The login timed out.", "Request / auth"),
  ("login required", 1, "Login required", "The page needs authentication.", "Request / auth"),
];

const kSignatures = <(String, int, String, String, String)>[..._sigsCore, ..._sigsDeep];
